const feed = [
  {
    nickname: "Jenny",
    avatar: "/avatar.png",
    image: [
      "/products/guardaroupa1.jpg",
      "/products/guardaroupa2.jpg",
      "/products/guardaroupa3.jpg",
    ],
    user_id: 1,
    location: "São Paulo",
    uf: "SP",
    description:
      "Procuro guarda-roupa, alguem com algo paerecido para a gente negociar?",
    likes: 4,
    comments: 10,
    price: 1000,
    posted: "2021-10-10T15:00:00",
  },
  {
    nickname: "Carlos",
    avatar: "/avatar.png",
    image: ["products/hondacivic1.jpg", "products/hondacivic2.jpg"],
    user_id: 1,
    location: "São Paulo",
    uf: "SP",
    description:
      "Estou desapegando do meu carro, honda civic 2002, 1.6, 16v, 4 portas, completo, confere lá!",
    likes: 11,
    comments: 9,
    price: 41000,
    posted: "2021-10-10T15:00:00",
  },
  {
    nickname: "Nigel",
    avatar: "/avatar.png",
    image: ["products/fusca.jpg"],
    user_id: 1,
    location: "São Paulo",
    uf: "SP",
    description:
      "Estou desapegando do meu carro, Fusca, 1.6, 16v, 2 portas, completo, maiores informações via inbox!",
    likes: 11,
    comments: 9,
    price: 15000,
    posted: "2021-10-10T15:00:00",
  },
  {
    nickname: "CrisBiJu",
    avatar: "/avatar.png",
    image: ["products/biju1.jpg", "products/biju2.jpg", "products/biju3.jpg"],
    user_id: 1,
    location: "São Paulo",
    uf: "SP",
    description: "Vendo bijuterias!",
    likes: 12,
    comments: 49,
    price: 50,
    posted: "2021-10-10T15:00:00",
  },
  {
    nickname: "k9 Canil",
    avatar: "/avatar.png",
    image: ["products/dog.jpg"],
    user_id: 1,
    location: "São Paulo",
    uf: "SP",
    description:
      "Estou procurando filhotes puros de pastor alemão, com pedigree, vacinados e vermifugados",
    likes: 41,
    comments: 29,
    price: 3000,
    posted: "2021-10-10T15:00:00",
  },
  {
    nickname: "Edi do celular",
    avatar: "/avatar.png",
    image: [
      "products/cel1.jpg",
      "products/cel2.jpg",
      "products/cel3.jpg",
      "products/cel1.jpg",
      "products/cel1.jpg",
    ],
    user_id: 1,
    location: "São Paulo",
    uf: "SP",
    description: "Procuro celulares iphones novos, diversos modelos e cores",
    likes: 1,
    comments: 91,
    price: 7000,
    posted: "2021-10-10T15:00:00",
  },
  {
    nickname: "tomTom",
    avatar: "/avatar.png",
    image: [
      "products/gtr1.jpg",
      "products/gtr2.jpg",
      "products/gtr3.jpg",
      "products/gtr4.jpg",
    ],
    user_id: 1,
    location: "São Paulo",
    uf: "SP",
    description:
      "procuro violoes gibson, fender, taylor, martin, takamine, yamaha, crafter, tagima, giannini, ibanez, epiphone, cort, strinberg, shelter, eagle, condor, memphis, phoenix",
    likes: 1,
    comments: 91,
    price: 7000,
    posted: "2021-10-10T15:00:00",
  },
];

export default feed;
